### ISSUE TITLE
Build error on fresh clone

### ISSUE THREAD

**Issue by jettdigital** [davidbuccola/force-authentication#2]
If I do a fresh git clone and then a gradlew build I get an error on the findBugs plugin

13:06:10.407 [DEBUG] [system.out] 13:06:10.407 [DEBUG] [org.gradle.process.internal.child.ActionExecutionWorker] Starting Gradle FindBugs Worker 1.
13:06:10.411 [DEBUG] [system.out] 13:06:10.411 [DEBUG] [org.gradle.api.plugins.quality.internal.findbugs.FindBugsWorkerServer] Executing FindBugs worker.
Scanning archives (50 / 50)m.out] 13:06:14.544 [QUIET] [system.out]
13:06:15.003 [DEBUG] [system.err] 13:06:15.002 [ERROR] [system.err] The following errors occurred during analysis:
13:06:15.004 [DEBUG] [system.err] 13:06:15.003 [ERROR] [system.err]   Unable to get XClass for java/lang/StringBuilder
13:06:15.004 [DEBUG] [system.err] 13:06:15.004 [ERROR] [system.err]     java.lang.ArrayIndexOutOfBoundsException: 5747
13:06:15.005 [DEBUG] [system.err] 13:06:15.004 [ERROR] [system.err]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
13:06:15.006 [DEBUG] [system.err] 13:06:15.006 [ERROR] [system.err]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
13:06:15.010 [DEBUG] [system.err] 13:06:15.009 [ERROR] [system.err]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
13:06:15.011 [DEBUG] [system.err] 13:06:15.010 [ERROR] [system.err]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
13:06:15.013 [DEBUG] [system.err] 13:06:15.013 [ERROR] [system.err]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
...
...

**Comment by davidbuccola** [comment]
Let me fix this right now. It looks like some sort of versioning problem. Should be easy to fix.

**Comment by davidbuccola** [comment]
I just fixed with commit 8a5ea4810762b41e4e308888d4404ebb0ccb855f. You can see the comment on that commit for a little more info on what was done.

**Comment by jettdigital** [comment]
works.

Can you make a note in README that gradle 2.3 is required? I usually just
do > gradle build instead of using the wrapper.

Thanks for the rapid replies btw!

**Comment by davidbuccola** [comment]
You should ALWAYS use the gradle wrapper when available. It is important for reliable builds. It makes sure you have the right gradle version to correspond to the project and also can contain any required environment setup. Like you, I hate typing "./gradlew". I therefore wrote the following bash function to make it really easy on Linux. It adaptively selects the right gradle. It looks first in the local project and then falls back on the global one if present.

   ```bash
function gradle {
    if [ -e "gradlew" ]; then
        ./gradlew $*
    else
        `which gradle` $*
    fi
}

```
